import express from 'express';
import cors from 'cors';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import fs from 'fs';
import path from 'path';
import multer from 'multer';
import sharp from 'sharp';
import { fileURLToPath } from 'url';
import { Pool } from 'pg';
import { DeleteObjectCommand, PutObjectCommand, S3Client } from '@aws-sdk/client-s3';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 5174;
const JWT_SECRET = process.env.ADMIN_JWT_SECRET || 'dev-secret-change-me';
const DATABASE_URL = process.env.DATABASE_URL;
const ADMIN_EMAIL = process.env.ADMIN_EMAIL;
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;
const R2_ACCOUNT_ID = process.env.R2_ACCOUNT_ID;
const R2_ACCESS_KEY_ID = process.env.R2_ACCESS_KEY_ID;
const R2_SECRET_ACCESS_KEY = process.env.R2_SECRET_ACCESS_KEY;
const R2_BUCKET_NAME = process.env.R2_BUCKET_NAME;
const R2_ENDPOINT =
  process.env.R2_ENDPOINT ||
  (R2_ACCOUNT_ID ? `https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com` : null);
const R2_PUBLIC_BASE_URL = process.env.R2_PUBLIC_BASE_URL;
const USE_SSL =
  process.env.PGSSLMODE === 'require' ||
  process.env.PGSSL === 'true' ||
  process.env.DATABASE_SSL === 'true';

const pool = new Pool({
  connectionString: DATABASE_URL,
  ssl: USE_SSL ? { rejectUnauthorized: false } : undefined,
});

app.use(cors());
app.use(express.json());

const upload = multer({
  storage: multer.memoryStorage(),
});

const getR2Client = () => {
  if (!R2_ENDPOINT || !R2_ACCESS_KEY_ID || !R2_SECRET_ACCESS_KEY) {
    return null;
  }

  return new S3Client({
    region: 'auto',
    endpoint: R2_ENDPOINT,
    credentials: {
      accessKeyId: R2_ACCESS_KEY_ID,
      secretAccessKey: R2_SECRET_ACCESS_KEY,
    },
  });
};

const r2Client = getR2Client();
const r2Configured = Boolean(r2Client && R2_BUCKET_NAME && R2_PUBLIC_BASE_URL);

const buildPublicUrl = (key) =>
  `${R2_PUBLIC_BASE_URL.replace(/\/+$/, '')}/${key}`;

const allowedMimeTypes = new Set(['image/jpeg', 'image/png', 'image/webp', 'image/avif']);

const normalizeFilenameBase = (filename = '') => {
  const cleaned = String(filename)
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/\.[^.]+$/, '')
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');

  return cleaned || 'foto';
};

const initDatabase = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS admin_users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS guest_families (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      family_name TEXT NOT NULL,
      access_code TEXT UNIQUE NOT NULL,
      phone TEXT,
      notes TEXT,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS family_members (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      family_id INTEGER NOT NULL REFERENCES guest_families(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS member_confirmations (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      member_id INTEGER NOT NULL REFERENCES family_members(id) ON DELETE CASCADE,
      attending BOOLEAN NOT NULL,
      dietary_restrictions TEXT,
      message TEXT,
      confirmed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS gallery_photos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT,
      file_key TEXT NOT NULL UNIQUE,
      file_url TEXT NOT NULL,
      thumb_key TEXT NOT NULL UNIQUE,
      thumb_url TEXT NOT NULL,
      mime_type TEXT NOT NULL,
      width INTEGER,
      height INTEGER,
      size_bytes BIGINT,
      sort_order INTEGER NOT NULL DEFAULT 0,
      is_active BOOLEAN NOT NULL DEFAULT true,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
  `);

  await pool.query(`
    ALTER TABLE family_members
    DROP COLUMN IF EXISTS relationship;
  `);
};

const withTransaction = async (fn) => {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const result = await fn(client);
    await client.query('COMMIT');
    return result;
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
  }
};

const generateAccessCode = () => {
  let code = '';
  for (let i = 0; i < 8; i += 1) {
    code += Math.floor(Math.random() * 10).toString();
  }
  return code;
};

const issueToken = (email) =>
  jwt.sign({ email }, JWT_SECRET, { expiresIn: '7d' });

const ensureAdminUser = async () => {
  if (!ADMIN_EMAIL || !ADMIN_PASSWORD) {
    return;
  }

  const normalizedEmail = ADMIN_EMAIL.trim().toLowerCase();
  const normalizedPassword = ADMIN_PASSWORD.trim();

  await pool.query(
    `INSERT INTO admin_users (email, password_hash)
     VALUES ($1, $2)
     ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash`,
    [normalizedEmail, bcrypt.hashSync(normalizedPassword, 10)]
  );
};

const authMiddleware = (req, res, next) => {
  const authHeader = req.headers.authorization || '';
  const token = authHeader.startsWith('Bearer ')
    ? authHeader.slice(7)
    : null;

  if (!token) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  try {
    const payload = jwt.verify(token, JWT_SECRET);
    req.user = payload;
    return next();
  } catch (err) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
};

const start = async () => {
  await initDatabase();
  await ensureAdminUser();

  app.get('/api/health', (_req, res) => {
    res.json({ ok: true });
  });

  app.get('/api/gallery-photos', async (_req, res) => {
    try {
      const galleryFromDb = await pool.query(
        `SELECT id, COALESCE(title, file_key) AS name, thumb_url AS path, file_url
         FROM gallery_photos
         WHERE is_active = true
         ORDER BY sort_order ASC, id ASC`
      );
      return res.json({ photos: galleryFromDb.rows });
    } catch (error) {
      console.error('Error loading gallery photos:', error);
      return res.status(500).json({ error: 'Erro ao carregar galeria.' });
    }
  });

  app.get('/api/gallery-photos/:id/download', async (req, res) => {
    const photoId = Number(req.params.id);
    if (!Number.isInteger(photoId) || photoId <= 0) {
      return res.status(400).json({ error: 'ID inválido.' });
    }

    try {
      const result = await pool.query(
        `SELECT id, COALESCE(title, file_key) AS name, file_url, mime_type
         FROM gallery_photos
         WHERE id = $1 AND is_active = true
         LIMIT 1`,
        [photoId]
      );
      const photo = result.rows[0];
      if (!photo) {
        return res.status(404).json({ error: 'Foto não encontrada.' });
      }

      const upstream = await fetch(photo.file_url);
      if (!upstream.ok) {
        return res.status(502).json({ error: 'Não foi possível baixar a foto de origem.' });
      }

      const bytes = Buffer.from(await upstream.arrayBuffer());
      const extMatch = String(photo.file_url).match(/\.[a-z0-9]+(?:\?|$)/i);
      const ext = extMatch ? extMatch[0].replace(/\?.*$/, '') : '.jpg';
      const safeBase = String(photo.name || 'foto')
        .normalize('NFD')
        .replace(/[\u0300-\u036f]/g, '')
        .replace(/[^a-zA-Z0-9._-]+/g, '-')
        .replace(/-+/g, '-')
        .replace(/^-|-$/g, '')
        .slice(0, 80) || 'foto';
      const filename = `${safeBase}${ext.toLowerCase()}`;

      res.setHeader('Content-Type', photo.mime_type || 'application/octet-stream');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
      return res.send(bytes);
    } catch (error) {
      console.error('Error downloading gallery photo:', error);
      return res.status(500).json({ error: 'Erro ao baixar foto.' });
    }
  });

  app.post('/api/admin/login', async (req, res) => {
    const { email, password } = req.body || {};
    if (!email || !password) {
      return res.status(400).json({ error: 'Email e senha são obrigatórios.' });
    }

    const normalizedEmail = String(email).trim().toLowerCase();
    const normalizedPassword = String(password).trim();
    const { rows } = await pool.query('SELECT * FROM admin_users WHERE lower(email) = $1', [
      normalizedEmail,
    ]);
    const user = rows[0];

    if (!user || !bcrypt.compareSync(normalizedPassword, user.password_hash)) {
      return res.status(401).json({ error: 'Login inválido.' });
    }

    return res.json({ token: issueToken(user.email), email: user.email });
  });

  app.get('/api/admin/session', authMiddleware, (req, res) => {
    res.json({ email: req.user.email });
  });

  app.get('/api/admin/families', authMiddleware, async (_req, res) => {
    const families = await pool.query('SELECT * FROM guest_families ORDER BY created_at DESC');
    const members = await pool.query('SELECT * FROM family_members ORDER BY created_at ASC');
    const confirmations = await pool.query(
      'SELECT * FROM member_confirmations ORDER BY confirmed_at DESC, id DESC'
    );

    res.json({
      families: families.rows,
      members: members.rows,
      confirmations: confirmations.rows,
    });
  });

  app.post('/api/admin/families', authMiddleware, async (req, res) => {
    const { family_name, phone, notes, members } = req.body || {};

    if (!family_name || !Array.isArray(members) || members.length === 0) {
      return res.status(400).json({ error: 'Nome da família e membros são obrigatórios.' });
    }

    let accessCode = generateAccessCode();

    for (let attempt = 0; attempt < 5; attempt += 1) {
      try {
        const result = await withTransaction(async (client) => {
          const insertFamily = await client.query(
            'INSERT INTO guest_families (family_name, access_code, phone, notes) VALUES ($1, $2, $3, $4) RETURNING *',
            [family_name.trim(), accessCode, phone?.trim() || null, notes?.trim() || null]
          );
          const family = insertFamily.rows[0];

          await Promise.all(
            members.map((member) =>
              client.query(
                'INSERT INTO family_members (family_id, name) VALUES ($1, $2)',
                [family.id, member.name.trim()]
              )
            )
          );

          const familyMembers = await client.query(
            'SELECT * FROM family_members WHERE family_id = $1 ORDER BY created_at ASC',
            [family.id]
          );

          return { family, members: familyMembers.rows };
        });

        return res.json(result);
      } catch (err) {
        if (String(err.message || '').includes('duplicate key') || String(err.message || '').includes('unique')) {
          accessCode = generateAccessCode();
        } else {
          console.error('Error:', err);
          return res.status(500).json({ error: 'Erro ao salvar família.' });
        }
      }
    }

    return res.status(500).json({ error: 'Não foi possível gerar código único.' });
  });

  app.put('/api/admin/families/:id', authMiddleware, async (req, res) => {
    const familyId = Number(req.params.id);
    const { family_name, phone, notes, members } = req.body || {};

    if (!familyId) {
      return res.status(400).json({ error: 'Família inválida.' });
    }

    if (!family_name || !Array.isArray(members) || members.length === 0) {
      return res.status(400).json({ error: 'Nome da família e membros são obrigatórios.' });
    }

    try {
      const result = await withTransaction(async (client) => {
        await client.query(
          'UPDATE guest_families SET family_name = $1, phone = $2, notes = $3 WHERE id = $4',
          [family_name.trim(), phone?.trim() || null, notes?.trim() || null, familyId]
        );

        const existingMembersResult = await client.query(
          'SELECT id FROM family_members WHERE family_id = $1',
          [familyId]
        );
        const existingMemberIds = new Set(existingMembersResult.rows.map((row) => row.id));
        const keptMemberIds = new Set();

        for (const member of members) {
          const name = member?.name?.trim();
          if (!name) continue;

          const memberId = Number(member?.id);

          if (memberId && existingMemberIds.has(memberId)) {
            await client.query(
              'UPDATE family_members SET name = $1 WHERE id = $2 AND family_id = $3',
              [name, memberId, familyId]
            );
            keptMemberIds.add(memberId);
          } else {
            const inserted = await client.query(
              'INSERT INTO family_members (family_id, name) VALUES ($1, $2) RETURNING id',
              [familyId, name]
            );
            keptMemberIds.add(inserted.rows[0].id);
          }
        }

        const membersToDelete = [...existingMemberIds].filter((id) => !keptMemberIds.has(id));
        if (membersToDelete.length > 0) {
          await client.query(
            'DELETE FROM family_members WHERE family_id = $1 AND id = ANY($2::int[])',
            [familyId, membersToDelete]
          );
        }

        const family = await client.query('SELECT * FROM guest_families WHERE id = $1', [familyId]);
        const familyMembers = await client.query(
          'SELECT * FROM family_members WHERE family_id = $1 ORDER BY created_at ASC',
          [familyId]
        );

        return { family: family.rows[0], members: familyMembers.rows };
      });

      return res.json(result);
    } catch (err) {
      console.error('Error:', err);
      return res.status(500).json({ error: 'Erro ao atualizar família.' });
    }
  });

  app.delete('/api/admin/families/:id', authMiddleware, async (req, res) => {
    const familyId = Number(req.params.id);

    if (!familyId) {
      return res.status(400).json({ error: 'Família inválida.' });
    }

    try {
      await withTransaction(async (client) => {
        await client.query('DELETE FROM family_members WHERE family_id = $1', [familyId]);
        await client.query('DELETE FROM guest_families WHERE id = $1', [familyId]);
      });

      return res.json({ ok: true });
    } catch (err) {
      console.error('Error:', err);
      return res.status(500).json({ error: 'Erro ao remover família.' });
    }
  });

  app.get('/api/admin/gallery-photos', authMiddleware, async (_req, res) => {
    try {
      const result = await pool.query(
        `SELECT id, title, file_key, file_url, thumb_key, thumb_url, mime_type, width, height,
                size_bytes, sort_order, is_active, created_at, updated_at
         FROM gallery_photos
         ORDER BY sort_order ASC, id ASC`
      );
      return res.json({ photos: result.rows, r2_configured: r2Configured });
    } catch (err) {
      console.error('Error loading admin gallery photos:', err);
      return res.status(500).json({ error: 'Erro ao carregar fotos da galeria.' });
    }
  });

  app.post('/api/admin/gallery-photos', authMiddleware, upload.single('photo'), async (req, res) => {
    if (!r2Configured) {
      return res.status(503).json({
        error: 'R2 nÃ£o configurado. Defina as variÃ¡veis de ambiente do R2 para habilitar upload.',
      });
    }

    const file = req.file;
    if (!file) {
      return res.status(400).json({ error: 'Arquivo da foto Ã© obrigatÃ³rio.' });
    }

    const allowedMimeTypes = new Set(['image/jpeg', 'image/png', 'image/webp', 'image/avif']);
    if (!allowedMimeTypes.has(file.mimetype)) {
      return res.status(400).json({ error: 'Formato invÃ¡lido. Use JPG, PNG, WebP ou AVIF.' });
    }

    try {
      const metadata = await sharp(file.buffer).metadata();
      const extension = file.mimetype === 'image/png' ? 'png' : file.mimetype === 'image/avif' ? 'avif' : file.mimetype === 'image/webp' ? 'webp' : 'jpg';
      const day = new Date().toISOString().slice(0, 10);
      const baseName = normalizeFilenameBase(file.originalname);
      let suffix = 0;
      let fileKey = '';
      let thumbKey = '';

      while (true) {
        const numbered = suffix === 0 ? baseName : `${baseName}-${suffix}`;
        const candidateFileKey = `originals/${day}/${numbered}.${extension}`;
        const candidateThumbKey = `thumbs/${day}/${numbered}.webp`;
        const conflict = await pool.query(
          'SELECT 1 FROM gallery_photos WHERE file_key = $1 OR thumb_key = $2 LIMIT 1',
          [candidateFileKey, candidateThumbKey]
        );

        if (conflict.rows.length === 0) {
          fileKey = candidateFileKey;
          thumbKey = candidateThumbKey;
          break;
        }

        suffix += 1;
      }
      const thumbBuffer = await sharp(file.buffer)
        .rotate()
        .resize({ width: 1200, withoutEnlargement: true })
        .webp({ quality: 82 })
        .toBuffer();

      await r2Client.send(
        new PutObjectCommand({
          Bucket: R2_BUCKET_NAME,
          Key: fileKey,
          Body: file.buffer,
          ContentType: file.mimetype,
        })
      );

      await r2Client.send(
        new PutObjectCommand({
          Bucket: R2_BUCKET_NAME,
          Key: thumbKey,
          Body: thumbBuffer,
          ContentType: 'image/webp',
        })
      );

      const fileUrl = buildPublicUrl(fileKey);
      const thumbUrl = buildPublicUrl(thumbKey);
      const title = (req.body?.title || '').trim() || `${baseName}.${extension}`;

      const inserted = await pool.query(
        `INSERT INTO gallery_photos
          (title, file_key, file_url, thumb_key, thumb_url, mime_type, width, height, size_bytes, sort_order, is_active)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 0, true)
         RETURNING *`,
        [
          title,
          fileKey,
          fileUrl,
          thumbKey,
          thumbUrl,
          file.mimetype,
          metadata.width || null,
          metadata.height || null,
          file.size,
        ]
      );

      return res.status(201).json({ photo: inserted.rows[0] });
    } catch (err) {
      console.error('Error uploading gallery photo:', err);
      return res.status(500).json({ error: 'Erro ao fazer upload da foto.' });
    }
  });

  app.delete('/api/admin/gallery-photos/:id', authMiddleware, async (req, res) => {
    if (!r2Configured) {
      return res.status(503).json({
        error: 'R2 nÃ£o configurado. Defina as variÃ¡veis de ambiente do R2 para habilitar remoÃ§Ã£o.',
      });
    }

    const photoId = Number(req.params.id);
    if (!Number.isInteger(photoId) || photoId <= 0) {
      return res.status(400).json({ error: 'ID invÃ¡lido.' });
    }

    try {
      const existing = await pool.query('SELECT * FROM gallery_photos WHERE id = $1', [photoId]);
      const photo = existing.rows[0];
      if (!photo) {
        return res.status(404).json({ error: 'Foto nÃ£o encontrada.' });
      }

      await Promise.all([
        r2Client.send(
          new DeleteObjectCommand({
            Bucket: R2_BUCKET_NAME,
            Key: photo.file_key,
          })
        ),
        r2Client.send(
          new DeleteObjectCommand({
            Bucket: R2_BUCKET_NAME,
            Key: photo.thumb_key,
          })
        ),
      ]);

      await pool.query('DELETE FROM gallery_photos WHERE id = $1', [photoId]);
      return res.json({ ok: true });
    } catch (err) {
      console.error('Error deleting gallery photo:', err);
      return res.status(500).json({ error: 'Erro ao remover foto.' });
    }
  });

  app.get('/api/access/:code', async (req, res) => {
    const code = (req.params.code || '').replace('-', '').trim();

    if (!code || code.length !== 8) {
      return res.status(400).json({ error: 'Código inválido.' });
    }

    const familyResult = await pool.query(
      'SELECT * FROM guest_families WHERE access_code = $1',
      [code]
    );
    const family = familyResult.rows[0];

    if (!family) {
      return res.status(404).json({ error: 'Código não encontrado.' });
    }

    const members = await pool.query(
      'SELECT * FROM family_members WHERE family_id = $1 ORDER BY created_at ASC',
      [family.id]
    );

    const confirmations = await pool.query(
      `SELECT DISTINCT ON (mc.member_id) mc.*
       FROM member_confirmations mc
       INNER JOIN family_members fm ON fm.id = mc.member_id
       WHERE fm.family_id = $1
       ORDER BY mc.member_id, mc.confirmed_at DESC, mc.id DESC`,
      [family.id]
    );

    return res.json({
      family,
      members: members.rows,
      confirmations: confirmations.rows,
    });
  });

  app.post('/api/confirmations', async (req, res) => {
    const { confirmations } = req.body || {};

    if (!Array.isArray(confirmations) || confirmations.length === 0) {
      return res.status(400).json({ error: 'Confirmações inválidas.' });
    }

    try {
      await withTransaction(async (client) => {
        await Promise.all(
          confirmations.map((item) =>
            client.query(
              `INSERT INTO member_confirmations
                (member_id, attending, dietary_restrictions, message, confirmed_at, updated_at)
               VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)`,
              [
                item.member_id,
                item.attending ? true : false,
                item.dietary_restrictions || null,
                item.message || null,
              ]
            )
          )
        );
      });

      return res.json({ ok: true });
    } catch (err) {
      console.error('Error:', err);
      return res.status(500).json({ error: 'Erro ao salvar confirmações.' });
    }
  });

  const distDir = path.join(__dirname, '../dist');
  if (fs.existsSync(distDir)) {
    app.use(express.static(distDir));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distDir, 'index.html'));
    });
  }

  app.listen(PORT, () => {
    console.log(`API running on http://localhost:${PORT}`);
  });
};

start();

