import bcrypt from 'bcryptjs';
import { Pool } from 'pg';

const email = process.env.ADMIN_EMAIL;
const password = process.env.ADMIN_PASSWORD;
const DATABASE_URL = process.env.DATABASE_URL;
const USE_SSL =
  process.env.PGSSLMODE === 'require' ||
  process.env.PGSSL === 'true' ||
  process.env.DATABASE_SSL === 'true';

if (!email || !password) {
  console.error('ADMIN_EMAIL e ADMIN_PASSWORD são obrigatórios.');
  process.exit(1);
}

const pool = new Pool({
  connectionString: DATABASE_URL,
  ssl: USE_SSL ? { rejectUnauthorized: false } : undefined,
});

const run = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS admin_users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
  `);

  const passwordHash = bcrypt.hashSync(password, 10);

  await pool.query(
    `INSERT INTO admin_users (email, password_hash)
     VALUES ($1, $2)
     ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash`,
    [email, passwordHash]
  );

  console.log('Admin criado/atualizado.');
  await pool.end();
};

run().catch((err) => {
  console.error('Erro ao criar admin:', err);
  process.exit(1);
});
